// Code generated by MockGen. DO NOT EDIT.
// Source: chart_repository.go
//
// Generated by this command:
//
//	mockgen -source=chart_repository.go -destination=mocks/mock_chart_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/truewebber/goitunes/v2/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockChartRepository is a mock of ChartRepository interface.
type MockChartRepository struct {
	ctrl     *gomock.Controller
	recorder *MockChartRepositoryMockRecorder
	isgomock struct{}
}

// MockChartRepositoryMockRecorder is the mock recorder for MockChartRepository.
type MockChartRepositoryMockRecorder struct {
	mock *MockChartRepository
}

// NewMockChartRepository creates a new mock instance.
func NewMockChartRepository(ctrl *gomock.Controller) *MockChartRepository {
	mock := &MockChartRepository{ctrl: ctrl}
	mock.recorder = &MockChartRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChartRepository) EXPECT() *MockChartRepositoryMockRecorder {
	return m.recorder
}

// GetTop1500 mocks base method.
func (m *MockChartRepository) GetTop1500(ctx context.Context, genreID string, chartType entity.ChartType, page, pageSize int) ([]*entity.ChartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTop1500", ctx, genreID, chartType, page, pageSize)
	ret0, _ := ret[0].([]*entity.ChartItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTop1500 indicates an expected call of GetTop1500.
func (mr *MockChartRepositoryMockRecorder) GetTop1500(ctx, genreID, chartType, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTop1500", reflect.TypeOf((*MockChartRepository)(nil).GetTop1500), ctx, genreID, chartType, page, pageSize)
}

// GetTop200 mocks base method.
func (m *MockChartRepository) GetTop200(ctx context.Context, genreID string, chartType entity.ChartType, kidPrefix string, from, limit int) ([]*entity.ChartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTop200", ctx, genreID, chartType, kidPrefix, from, limit)
	ret0, _ := ret[0].([]*entity.ChartItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTop200 indicates an expected call of GetTop200.
func (mr *MockChartRepositoryMockRecorder) GetTop200(ctx, genreID, chartType, kidPrefix, from, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTop200", reflect.TypeOf((*MockChartRepository)(nil).GetTop200), ctx, genreID, chartType, kidPrefix, from, limit)
}
