// Code generated by MockGen. DO NOT EDIT.
// Source: application_repository.go
//
// Generated by this command:
//
//	mockgen -source=application_repository.go -destination=mocks/mock_application_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/truewebber/goitunes/v2/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockApplicationRepository is a mock of ApplicationRepository interface.
type MockApplicationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockApplicationRepositoryMockRecorder
	isgomock struct{}
}

// MockApplicationRepositoryMockRecorder is the mock recorder for MockApplicationRepository.
type MockApplicationRepositoryMockRecorder struct {
	mock *MockApplicationRepository
}

// NewMockApplicationRepository creates a new mock instance.
func NewMockApplicationRepository(ctrl *gomock.Controller) *MockApplicationRepository {
	mock := &MockApplicationRepository{ctrl: ctrl}
	mock.recorder = &MockApplicationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplicationRepository) EXPECT() *MockApplicationRepositoryMockRecorder {
	return m.recorder
}

// FindByAdamID mocks base method.
func (m *MockApplicationRepository) FindByAdamID(ctx context.Context, adamIDs []string) ([]*entity.Application, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByAdamID", ctx, adamIDs)
	ret0, _ := ret[0].([]*entity.Application)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByAdamID indicates an expected call of FindByAdamID.
func (mr *MockApplicationRepositoryMockRecorder) FindByAdamID(ctx, adamIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByAdamID", reflect.TypeOf((*MockApplicationRepository)(nil).FindByAdamID), ctx, adamIDs)
}

// FindByBundleID mocks base method.
func (m *MockApplicationRepository) FindByBundleID(ctx context.Context, bundleIDs []string) ([]*entity.Application, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByBundleID", ctx, bundleIDs)
	ret0, _ := ret[0].([]*entity.Application)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByBundleID indicates an expected call of FindByBundleID.
func (mr *MockApplicationRepositoryMockRecorder) FindByBundleID(ctx, bundleIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByBundleID", reflect.TypeOf((*MockApplicationRepository)(nil).FindByBundleID), ctx, bundleIDs)
}

// GetFullInfo mocks base method.
func (m *MockApplicationRepository) GetFullInfo(ctx context.Context, adamID string) (*entity.Application, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFullInfo", ctx, adamID)
	ret0, _ := ret[0].(*entity.Application)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFullInfo indicates an expected call of GetFullInfo.
func (mr *MockApplicationRepositoryMockRecorder) GetFullInfo(ctx, adamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFullInfo", reflect.TypeOf((*MockApplicationRepository)(nil).GetFullInfo), ctx, adamID)
}

// GetOverallRating mocks base method.
func (m *MockApplicationRepository) GetOverallRating(ctx context.Context, adamID string) (*entity.Rating, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOverallRating", ctx, adamID)
	ret0, _ := ret[0].(*entity.Rating)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOverallRating indicates an expected call of GetOverallRating.
func (mr *MockApplicationRepositoryMockRecorder) GetOverallRating(ctx, adamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOverallRating", reflect.TypeOf((*MockApplicationRepository)(nil).GetOverallRating), ctx, adamID)
}

// GetRating mocks base method.
func (m *MockApplicationRepository) GetRating(ctx context.Context, adamID string) (*entity.Rating, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRating", ctx, adamID)
	ret0, _ := ret[0].(*entity.Rating)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRating indicates an expected call of GetRating.
func (mr *MockApplicationRepositoryMockRecorder) GetRating(ctx, adamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRating", reflect.TypeOf((*MockApplicationRepository)(nil).GetRating), ctx, adamID)
}
