// Code generated by MockGen. DO NOT EDIT.
// Source: purchase_repository.go
//
// Generated by this command:
//
//	mockgen -source=purchase_repository.go -destination=mocks/mock_purchase_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/truewebber/goitunes/v2/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockPurchaseRepository is a mock of PurchaseRepository interface.
type MockPurchaseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPurchaseRepositoryMockRecorder
	isgomock struct{}
}

// MockPurchaseRepositoryMockRecorder is the mock recorder for MockPurchaseRepository.
type MockPurchaseRepositoryMockRecorder struct {
	mock *MockPurchaseRepository
}

// NewMockPurchaseRepository creates a new mock instance.
func NewMockPurchaseRepository(ctrl *gomock.Controller) *MockPurchaseRepository {
	mock := &MockPurchaseRepository{ctrl: ctrl}
	mock.recorder = &MockPurchaseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPurchaseRepository) EXPECT() *MockPurchaseRepositoryMockRecorder {
	return m.recorder
}

// ConfirmDownload mocks base method.
func (m *MockPurchaseRepository) ConfirmDownload(ctx context.Context, downloadID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmDownload", ctx, downloadID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmDownload indicates an expected call of ConfirmDownload.
func (mr *MockPurchaseRepositoryMockRecorder) ConfirmDownload(ctx, downloadID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmDownload", reflect.TypeOf((*MockPurchaseRepository)(nil).ConfirmDownload), ctx, downloadID)
}

// Purchase mocks base method.
func (m *MockPurchaseRepository) Purchase(ctx context.Context, adamID string, versionID int64) (*entity.DownloadInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Purchase", ctx, adamID, versionID)
	ret0, _ := ret[0].(*entity.DownloadInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Purchase indicates an expected call of Purchase.
func (mr *MockPurchaseRepositoryMockRecorder) Purchase(ctx, adamID, versionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Purchase", reflect.TypeOf((*MockPurchaseRepository)(nil).Purchase), ctx, adamID, versionID)
}
